declare const window: Window & typeof globalThis;
declare const document: Document;
declare const navigator: Navigator;
declare const localStorage: Storage;
declare const sessionStorage: Storage;
declare const console: Console;
declare const fetch: typeof globalThis.fetch;
declare const setTimeout: typeof globalThis.setTimeout;
declare const clearTimeout: typeof globalThis.clearTimeout;
declare const requestAnimationFrame: typeof globalThis.requestAnimationFrame;
declare const cancelAnimationFrame: typeof globalThis.cancelAnimationFrame;
declare const performance: Performance;
declare const IntersectionObserver: typeof globalThis.IntersectionObserver;
declare const AbortController: typeof globalThis.AbortController;
declare const URL: typeof globalThis.URL;
declare const URLSearchParams: typeof globalThis.URLSearchParams;
declare const Event: typeof globalThis.Event;
declare const CustomEvent: typeof globalThis.CustomEvent;
declare const HTMLElement: typeof globalThis.HTMLElement;
declare const HTMLInputElement: typeof globalThis.HTMLInputElement;
declare const MutationObserver: typeof globalThis.MutationObserver;
declare const requestIdleCallback: typeof globalThis.requestIdleCallback;
declare const cancelIdleCallback: typeof globalThis.cancelIdleCallback;
declare const globalThis: typeof globalThis;
